export const ADD_TO_ORDER = "ADD_TO_ORDER";
export const REMOVE_FROM_ORDER = "REMOVE_FROM_ORDER";
export const ADJUST_QUANTITY = "ADJUST_QUANTITY";
export const LOAD_CURRENT_ITEM = "LOAD_CURRENT_ITEM";
